import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,readdirSync,rmSync,writeFileSync,mkdirSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {spawnSync} from 'node:child_process';
import Core from '../assets/core.js';import {downsample,atomicJSON,publicSnapshot,assertPublic} from '../scripts/lib/io.mjs';
import {treasury,parseTransfers} from '../scripts/lib/treasury.mjs';import {reconcile,saveSnapshot} from '../scripts/lib/snapshot.mjs';import {accrue} from '../scripts/lib/accrual.mjs';import {simulate,forecastFund,nextPayday} from '../scripts/lib/forecast.mjs';
const now=Date.parse('2026-09-26T06:00:00Z'),DAY=86400000;
const cfg={owners:[{id:'a',name:'A'}],events:[{id:'initial',date:'2026-09-01',owner:'a',type:'deposit',usd:10000,founding:true}],fund:{fixedCapitalUsd:8000,capacityUsd:8000},costs:{items:[]},dividend:{basis:'treasury',distributePct:100,reinvestPct:0,payDayOfMonth:1},treasury:{openingUsd:0,stepUsd:100}};
test('downsampling keeps a representative even when cron misses the usual minute',()=>{const a={t:now-20*DAY+13*60000,usd:10},b={t:a.t+3600000,usd:11};const r=downsample([a,b],now);assert.equal(r.length,1);assert.equal(r[0].usd,11);});
test('treasury IDs deduplicate only real identities and debit payments',()=>{const bot=[{at:now,amountUsd:100,tx:'tx1'}];assert.equal(treasury(cfg,bot,[{at:now,usd:100,tx:'tx1'}]).treasuryUsd,100);assert.throws(()=>treasury(cfg,bot,[{at:now,usd:100}]));const r=treasury(cfg,bot,[{id:'second',at:now+1,usd:100},{id:'paid',type:'dividend',at:now+2,usd:60}]);assert.equal(r.treasuryUsd,140);assert.equal(r.dividendLayers.reduce((t,l)=>t+l.usd,0),140);assert.equal(r.outflowTotalUsd,60);assert.throws(()=>parseTransfers('{"broken":'));});
test('snapshot total uses one component set and fees only once',()=>{const s={updatedAt:now,holdings:[{usd:100}],positions:[{principalUsd:80,feesUsd:5,investedUsd:90,collectedFeesUsd:10}],treasuryUsd:20};reconcile(s,cfg);assert.equal(s.totalUsd,205);assert.equal(s.positions[0].valueUsd,85);assert.equal(s.positions[0].pnlUsd,5);assert.throws(()=>reconcile({...s,holdings:[{usd:null}]},cfg));});
test('abnormal NAV is rejected before publishing any files',()=>{const d=mkdtempSync(join(tmpdir(),'cashood-test-'));try{const out=join(d,'live.json');const s={updatedAt:now,holdings:[{usd:100}],positions:[],treasuryUsd:0};saveSnapshot(out,s,cfg);const before=readFileSync(out,'utf8');assert.throws(()=>saveSnapshot(out,{updatedAt:now+100,holdings:[{usd:1}],positions:[]},cfg));assert.equal(readFileSync(out,'utf8'),before);}finally{rmSync(d,{recursive:true,force:true});}});
test('public position IDs are stable opaque IDs and raw secrets are rejected',()=>{const d=mkdtempSync(join(tmpdir(),'cashood-test-'));try{const s={positions:[{tokenId:'123',principalUsd:5,feesUsd:1}],closedRecent:[{tokenId:'123'}]};const a=publicSnapshot(s,d),b=publicSnapshot(s,d);assert.equal(a.positions[0].tokenId,b.positions[0].tokenId);assert.match(a.positions[0].tokenId,/^pos-/);assert.equal(a.closedRecent[0].tokenId,undefined);assert.throws(()=>assertPublic({address:'0x'+'a'.repeat(40)}));}finally{rmSync(d,{recursive:true,force:true});}});
test('atomic writes leave no temporary files',()=>{const d=mkdtempSync(join(tmpdir(),'cashood-test-'));try{atomicJSON(join(d,'data.json'),{ok:1});assert.deepEqual(readdirSync(d),['data.json']);}finally{rmSync(d,{recursive:true,force:true});}});
const sb={owners:[{id:'a',name:'A',principalUsd:3000}],rate:{minMonthlyPct:0,maxMonthlyPct:3}};
test('Safe Box first-day growth is captured and invalid fee never enters accrual',()=>{let s=accrue(sb,null,{at:now,fee:10});s=accrue(sb,s,{at:now+3600000,fee:10.1});assert.ok(s.balances.a.accrued>0);assert.throws(()=>accrue(sb,s,{at:now+7200000,fee:Infinity}));});
test('Safe Box downtime is allocated to elapsed days, not capped as one day',()=>{const start=Core.eventTime({date:'2026-09-20'});let s=accrue(sb,null,{at:start,fee:0});s=accrue(sb,s,{at:start+2*DAY,fee:10});assert.equal(s.days.length,2);assert.equal(s.balances.a.accrued,6);assert.ok(s.days.every(d=>d.estimated));});
test('new Safe Box owner does not receive old accrual and payouts lower outstanding balance',()=>{let s=accrue(sb,null,{at:now,fee:0});s=accrue(sb,s,{at:now+DAY,fee:1});const changed={...sb,ownerEvents:[{at:now+DAY+1,owners:[...sb.owners,{id:'b',name:'B',principalUsd:3000}]}]};s=accrue(changed,s,{at:now+2*DAY,fee:2});assert.ok(s.balances.a.accrued>s.balances.b.accrued);s=accrue(changed,s,{at:now+2*DAY,fee:2},null,[{id:'pay1',owner:'a',type:'interest',at:now+2*DAY,usd:.5}]);assert.equal(s.balances.a.paid,.5);});
test('zero-market-change sweeps do not create simulated investor loss',()=>{const r=simulate({cfg,live:{totalUsd:10000,treasuryUsd:0},daily:[{pct:0}],now,days:[1,7],paths:1})[0];assert.equal(r[1].working,8000);assert.equal(r[1].cash,2000);assert.equal(r[1].low,10000);assert.equal(r[7].total,10000);assert.equal(r[7].paid,2000);});
test('forecast refuses legacy/unverified NAV instead of inventing probabilities',()=>{const r=forecastFund('test',cfg,{totalUsd:10000,updatedAt:now,quality:{complete:true}},[{t:now-DAY,usd:10000}],{now,paths:1});assert.equal(r.enough,false);});
test('forecast source dates exclude incomplete day and adjust external deposits',()=>{
 const points=Array.from({length:10},(_,i)=>({t:now-(10-i)*DAY,usd:10000,quality:'complete',outflowTotalUsd:0}));
 const r=forecastFund('test',cfg,{totalUsd:10000,updatedAt:now,treasuryUsd:0,quality:{complete:true},positions:[],history:[]},points,{now,paths:20});assert.equal(r.enough,true);assert.equal(r.horizons[0].risk.p10,0);assert.equal(r.horizons[0].normal.totalUsd,10000);assert.equal(r.horizons[0].normal.navUsd+r.horizons[0].normal.dividendsUsd,r.horizons[0].normal.totalUsd);
});
test('record CLI refuses duplicate IDs and preserves historical time',()=>{const dir=mkdtempSync(join(tmpdir(),'cashood-record-'));try{mkdirSync(join(dir,'reborn'));atomicJSON(join(dir,'reborn/config.json'),cfg);const run=(args)=>spawnSync(process.execPath,['scripts/record.mjs',...args],{cwd:resolve('.'),env:{...process.env,CASHOOD_DATA_DIR:dir},encoding:'utf8'});const args=['deposit','a','100','--id','test-deposit','--at','2026-09-02T05:00:00Z','--nav','10000'];assert.equal(run(args).status,0);assert.notEqual(run(args).status,0);const e=JSON.parse(readFileSync(join(dir,'reborn/config.json'))).events.at(-1);assert.equal(e.at,Date.parse('2026-09-02T05:00:00Z'));}finally{rmSync(dir,{recursive:true,force:true});}});
test('statement creates frozen revision and refuses overwrite',()=>{const dir=mkdtempSync(join(tmpdir(),'cashood-statement-'));try{mkdirSync(join(dir,'reborn'));atomicJSON(join(dir,'reborn/config.json'),cfg);const report=join(dir,'reports');const args=['scripts/statement.mjs','--withdrawn','100','--rate','17000','--period','2026-09','--html-only'];const options={env:{...process.env,CASHOOD_DATA_DIR:dir,CASHOOD_REPORTS_DIR:report},encoding:'utf8'};const first=spawnSync(process.execPath,args,options);assert.equal(first.status,0,first.stderr);assert.notEqual(spawnSync(process.execPath,args,options).status,0);assert.equal(readdirSync(join(report,'private')).length,1);}finally{rmSync(dir,{recursive:true,force:true});}});

test('investor fees reduce received dividends, while paid costs are not charged twice',()=>{const c={...cfg,costs:{items:[{usd:100}]},dividend:{...cfg.dividend,investorFeePct:10}};const r=simulate({cfg:c,live:{totalUsd:10000,treasuryUsd:2000,costsPaidUsd:100},daily:[{pct:0}],now,days:[7],paths:1})[0][7];assert.equal(r.paid,1800);assert.equal(r.total,9800);});
test('Safe Box rejects backdated ownership edits instead of silently ignoring them',()=>{const s=accrue(sb,null,{at:now,fee:0});assert.throws(()=>accrue({...sb,ownerEvents:[{at:now-1,owners:sb.owners}]},s,{at:now+1,fee:0}),/Riwayat/);});

test('snapshot guard allows recorded payouts and cannot override stale quality',()=>{const s={updatedAt:now,holdings:[{usd:5000}],positions:[],treasuryUsd:0,outflowTotalUsd:5000};reconcile(s,cfg,{updatedAt:now-1,totalUsd:10000,outflowTotalUsd:0});assert.equal(s.totalUsd,5000);const stale={updatedAt:now,holdings:[],positions:[{principalUsd:10,feesUsd:1,stale:true}],quality:{complete:true}};reconcile(stale,cfg);assert.equal(stale.quality.complete,false);});
test('invoice freezes actual treasury layers and stays reproducible after live data changes',()=>{const dir=mkdtempSync(join(tmpdir(),'cashood-invoice-'));try{mkdirSync(join(dir,'reborn'));const period=Core.day(Date.now()).slice(0,7);atomicJSON(join(dir,'reborn/config.json'),cfg);const live={updatedAt:Date.now(),totalUsd:11000,holdings:[{usd:10000}],positions:[],treasuryUsd:1000,dividendLayers:[{usd:1000,before:Date.now()}],quality:{complete:true}};atomicJSON(join(dir,'reborn/live.json'),live);const report=join(dir,'reports'),opts={env:{...process.env,CASHOOD_DATA_DIR:dir,CASHOOD_REPORTS_DIR:report},encoding:'utf8'};const first=spawnSync(process.execPath,['scripts/statement.mjs','--from-live','--rate','17000','--period',period,'--html-only'],opts);assert.equal(first.status,0,first.stderr);const input=join(report,'private',readdirSync(join(report,'private'))[0]),frozen=JSON.parse(readFileSync(input));assert.equal(frozen.plan.received,1000);atomicJSON(join(dir,'reborn/live.json'),{...live,treasuryUsd:0});const second=spawnSync(process.execPath,['scripts/statement.mjs','--snapshot',input,'--revision','2','--html-only'],opts);assert.equal(second.status,0,second.stderr);const files=readdirSync(join(report,'private'));assert.deepEqual(JSON.parse(readFileSync(join(report,'private',files[1]))).rows,frozen.rows);}finally{rmSync(dir,{recursive:true,force:true});}});
